#!/usr/bin/env sh

######################################################################
# @author      : Justin Kachele (justin@kachele.com)
# @file        : temps
# @created     : Monday Aug 07, 2023 20:58:38 EDT
#
# @description : 
######################################################################

gpu=`nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits`
cpu=`sensors | grep Tctl`

readarray -d "+" -t cpu <<< "$cpu"
readarray -d "." -t cpu <<< "${cpu[1]}"
# read -r cpu <<<"${cpu//[$'\t\r\n']}"

# printf "CPU: %s°C GPU: %s°C\n" "${cpu[0]}" "$gpu"
printf "CPU: %sC GPU: %sC\n" "${cpu[0]}" "$gpu"
